name: CI
permissions:
  contents: read
  statuses: write

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
   run-ci-test:
        name: ci-run-test
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '22'

        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm test

      
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v4
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}